Feature/#18 stadium service
matrixpower1004/fastcampus-baseball pull request #21
Opened 2023-06-27 09:39 UTC by Horaiz-UQ

- [ ] stadium service 구현
- [ ] stadium service Test 구현

2023-06-27 10:11 UTC, matrixpower1004 commented on src/test/java/team/snowball/baseball/service/StadiumServiceTest.java
> +        StadiumDao stadiumDao = new StadiumDao();
테스트는 외부에서 호출하는 서비스가 아니니까  Statidum Service를 private로 선언했다면 dao도 같이 pirvate 로 선언해서 통일성을 가지는 게 좋지 않을까요?

2023-06-27 10:15 UTC, matrixpower1004 commented on src/test/java/team/snowball/baseball/service/StadiumServiceTest.java
> +        for (Stadium stadium : stadiums) {
Insert가 제대로 되었는지 확인하는데 전체 야구장을 모두 순회해야 할 필요가 있을까요? DB 특성 상 제일 마지막 데이터가 Insert 된 데이터니까 제일 마지막 데이터가 내가 insert한 데이터가 맞는지 확인하거나,
Inset 하기 전의 배열 length와 Inset 후의 배열 length를 비교하는 것 만으로도 충분할 것 같다고 생각되네요.

2023-06-27 10:16 UTC, matrixpower1004 commented on src/main/java/team/snowball/baseball/service/StadiumService.java
> +}
소스 끝에 빈 라인 하나 더 추가해서 - 기호 없애주세요.

2023-06-27 10:20 UTC, matrixpower1004 commented on src/test/java/team/snowball/baseball/service/StadiumServiceTest.java
> +}
소스 끝에 빈 라인 하나 더 추가해서 - 기호 없애주세요.

2023-06-27 10:21 UTC, matrixpower1004 commented on src/main/java/team/snowball/baseball/dao/StadiumDao.java
> +        connection = SnowballDBManager.getConnection();
Dao 공통으로 insert, delete, update에 트랙잰셕 적용해 주세요.

2023-06-27 10:22 UTC, Horaiz-UQ commented on src/main/java/team/snowball/baseball/dao/StadiumDao.java
> +        connection = SnowballDBManager.getConnection();
네 같이 수정해서 PR드리겠습니다

2023-06-27 10:28 UTC, matrixpower1004 commented on src/main/java/team/snowball/baseball/service/StadiumService.java
> +        Stadium stadium = new Stadium(null, name, null);
model 객체 생성에 Builder 패턴 적용하지 않았나요? 저 코드만 보고 다른 팀원이 인자로 왜 null이 들어가야 하는지 이해가 될까요? 그리고 null이 들어가도 된다면 저 null은 어떤 필드인지 코드 작성하지 않은 사람은 한번 더 model 코드를 찾아봐야 되지 않을까요?
Staduim stadium = Staduim.builder()
		.name(name)
		.build();
빌더 패턴 적용한 위 코드와 용원님이 작성한 코드 중 어느 것이 더 가독성이 좋다고 생각하시나요?

2023-06-27 10:31 UTC, Horaiz-UQ commented on src/main/java/team/snowball/baseball/service/StadiumService.java
> +        Stadium stadium = new Stadium(null, name, null);
다시 수정해 놓겠습니다 알려주셔서 감사합니다!

2023-06-27 10:34 UTC, matrixpower1004 requested changes
제가 리뷰 해 드린 내용 반영해서 다시 pr 주세요. 제 의견이 무조건 정답은 아니니 다른 합당하다고 생각하는 의견이 있다면 제시해 주세요.

2023-06-28 04:21 UTC, matrixpower1004 commented on src/main/java/team/snowball/baseball/dao/StadiumDao.java
> +                System.out.println("업데이트 성공");
이 부분 ToDo 에 기록해 두셨다가 출력 메시지 Enum에서 받는 로직으로 변경해 주세요.

2023-06-28 04:30 UTC, matrixpower1004 approved these changes
👍

2023-06-28 04:31 UTC, matrixpower1004 approved these changes
👍

2023-06-28 04:32 UTC, merged